#!/bin/sh

cd ~/boost/libs

#mv ~/boost.list ~/boost.list2
#du -sb */include */src numeric/*/include | sort -n > ~/boost.list

read -r -d '' list << EOM
    static_assert
    #disjoint_sets
    lambda2
    assert
    conversion
    #compatibility
    array
    typeof
    ratio
    throw_exception
    parameter_python
    logic
    tokenizer
    io
    timer
    rational
    align
    container_hash
    property_map
    foreach
    tuple
    any
    scope_exit
    describe
    integer
    assign
    convert
    function
    property_map_parallel
    coroutine2
    bloom
    bind
    concept_check
    type_index
    functional
    detail
    variant2
    exception
    #chrono/stopwatches
    crc
    compat
    endian
    #signals
    lexical_cast
    multi_array
    optional
    stacktrace
    flyweight
    #tr1
    stl_interfaces
    format
    lockfree
    numeric/conversion
    nowide
    pool
    scope
    yap
    system
    numeric/interval
    statechart
    dynamic_bitset
    mp11
    iterator
    variant
    uuid
    static_string
    smart_ptr
    callable_traits
    signals2
    local_function
    program_options
    leaf
    heap
    tti
    coroutine
    safe_numerics
    hash2
    predef
    dll
    poly_collection
    ptr_container
    utility
    circular_buffer
    core
    hof
    fiber
    redis
    property_tree
    mqtt5
    chrono
    #sync
    histogram
    lambda
    cobalt
    contract
    bimap
    type_erasure
    config
    move
    winapi
    metaparse
    algorithm
    accumulators
    mpi
    filesystem
    sort
    multi_index
    context
    icl
    range
    iostreams
    function_types
    units
    parameter
    date_time
    locale
    vmd
#
    openmethod
    outcome
    unordered
    regex
    serialization
    python
    xpressive
    charconv
    graph_parallel
    process
    random
    type_traits
    numeric/odeint
    test
    msm
    json
    pfr
    url
    thread
    wave
    atomic
    polygon
    parser
    compute
    gil
    interprocess
    intrusive
    proto
    mysql
    decimal
    beast
    log
    qvm
    graph
    multiprecision
    numeric/ublas
    container
    hana
    mpl
    asio
    spirit
    math
    preprocessor
    geometry
    fusion
    phoenix
    #headers
EOM
for d in $list
do
  if [[ $d != '#'* ]]; then
    cd $d
    pwd
    wc -l include/boost/* include/boost/*/* include/boost/*/*/* include/boost/*/*/*/* include/boost/*/*/*/*/* include/boost/*/*/*/*/*/* include/boost/*/*/*/*/*/*/* include/boost/*/*/*/*/*/*/*/* include/boost/*/*/*/*/*/*/*/*/* src/* src/*/* src/*/*/* src/*/*/*/* extras/src/*
    du -sb .
    cd -
  fi
done
